package generator

import (
	"fmt"
	"strings"

	"macro-engine/internal/model"
)

// Generator 脚本生成器
type Generator struct {
}

// NewGenerator 创建新的生成器
func NewGenerator() *Generator {
	return &Generator{}
}

// Generate 生成脚本
func (g *Generator) Generate(name string, events []model.Event) (string, error) {
	var sb strings.Builder

	// 头部
	sb.WriteString(fmt.Sprintf(`// Macro: %s
// Generated by MacroRecorder
// Events: %d

function main() {
`, name, len(events)))

	// 优化事件
	optimizedEvents := g.optimizeEvents(events)

	// 生成事件处理代码
	for i, ev := range optimizedEvents {
		// 添加延迟（基于时间戳差值）
		if i > 0 {
			delay := ev.Timestamp - optimizedEvents[i-1].Timestamp
			if delay > 10 {
				sb.WriteString(fmt.Sprintf("  sleep(%d);\n", delay))
			}
		}

		switch ev.Type {
		case model.EventTypeMouseMove:
			sb.WriteString(fmt.Sprintf("  mouseMove(%d, %d);\n", ev.X, ev.Y))

		case model.EventTypeMouseDown:
			btn := g.getMouseButtonName(ev.Button)
			sb.WriteString(fmt.Sprintf("  mouseClick('%s'); // down\n", btn))

		case model.EventTypeMouseUp:
			// mouseup 通常不需要单独处理，因为 click 已经包含

		case model.EventTypeWheel:
			sb.WriteString(fmt.Sprintf("  mouseScroll(%d);\n", ev.Delta))

		case model.EventTypeKeyDown:
			keyName := g.getKeyName(ev.KeyCode)
			sb.WriteString(fmt.Sprintf("  keyDown('%s');\n", keyName))

		case model.EventTypeKeyUp:
			keyName := g.getKeyName(ev.KeyCode)
			sb.WriteString(fmt.Sprintf("  keyUp('%s');\n", keyName))
		}
	}

	sb.WriteString(`}

main();
`)

	return sb.String(), nil
}

// optimizeEvents 优化事件序列
func (g *Generator) optimizeEvents(events []model.Event) []model.Event {
	if len(events) == 0 {
		return events
	}

	// 移除重复的 mousemove 事件（保留最新的）
	optimized := make([]model.Event, 0)
	lastMouseMove := model.Event{}

	for _, ev := range events {
		if ev.Type == model.EventTypeMouseMove {
			// 如果是连续的 mousemove，只保留最后一个
			lastMouseMove = ev
		} else {
			// 如果有累积的 mousemove，先添加它
			if lastMouseMove.Type != "" {
				optimized = append(optimized, lastMouseMove)
				lastMouseMove = model.Event{}
			}
			optimized = append(optimized, ev)
		}
	}

	return optimized
}

// getMouseButtonName 获取鼠标按钮名称
func (g *Generator) getMouseButtonName(btn model.MouseButton) string {
	switch btn {
	case model.MouseButtonLeft:
		return "left"
	case model.MouseButtonRight:
		return "right"
	case model.MouseButtonMiddle:
		return "middle"
	default:
		return "left"
	}
}

// getKeyName 获取按键名称
func (g *Generator) getKeyName(keyCode int) string {
	// 常见键值映射
	keyMap := map[int]string{
		1:   "left",
		2:   "right",
		4:   "middle",
		13:  "enter",
		27:  "escape",
		32:  "space",
		37:  "left",
		38:  "up",
		39:  "right",
		40:  "down",
		46:  "delete",
		112: "f1",
		113: "f2",
		114: "f3",
		115: "f4",
		116: "f5",
		117: "f6",
		118: "f7",
		119: "f8",
		120: "f9",
		121: "f10",
		122: "f11",
		123: "f12",
	}

	if name, ok := keyMap[keyCode]; ok {
		return name
	}

	// 返回单个字符
	return string(rune(keyCode))
}
