package generator

import (
	"fmt"
	"strings"

	"macro-engine/internal/model"
)

// Generator 脚本生成器
type Generator struct {
	MinDelayThreshold int // 最小延迟阈值（毫秒），小于此值不输出 sleep
}

// GeneratorOption 生成器配置选项
type GeneratorOption func(*Generator)

// WithMinDelayThreshold 设置最小延迟阈值
func WithMinDelayThreshold(threshold int) GeneratorOption {
	return func(g *Generator) {
		g.MinDelayThreshold = threshold
	}
}

// NewGenerator 创建新的生成器
func NewGenerator(opts ...GeneratorOption) *Generator {
	g := &Generator{
		MinDelayThreshold: 50, // 默认 50ms 阈值
	}
	for _, opt := range opts {
		opt(g)
	}
	return g
}

// GenerateWithConfig 使用指定配置生成脚本
func (g *Generator) GenerateWithConfig(name string, events []model.Event, minDelay int) (string, error) {
	// 临时修改阈值
	oldThreshold := g.MinDelayThreshold
	g.MinDelayThreshold = minDelay
	defer func() { g.MinDelayThreshold = oldThreshold }()

	return g.Generate(name, events)
}

// Generate 生成脚本
func (g *Generator) Generate(name string, events []model.Event) (string, error) {
	var sb strings.Builder

	// 头部
	sb.WriteString(fmt.Sprintf(`// 宏录制脚本: %s
// Generated by MacroRecorder
// Events: %d
// Note: Uses raw keyboard events (KeyDown/KeyUp) for IME compatibility

function main() {
`, name, len(events)))

	// 优化事件
	optimizedEvents := g.optimizeEvents(events)

	// 生成事件处理代码
	var accumulatedDelay int64 = 0
	lastEventType := model.EventType(0)

	for i, ev := range optimizedEvents {
		// 计算延迟
		if i > 0 {
			delay := ev.Timestamp - optimizedEvents[i-1].Timestamp

			// 智能判断是否需要添加 sleep
			needSleep := g.shouldAddSleep(ev.Type, lastEventType, delay, accumulatedDelay)

			if needSleep {
				// 输出累积的延迟
				totalDelay := accumulatedDelay + delay
				if totalDelay >= int64(g.MinDelayThreshold) {
					sb.WriteString(fmt.Sprintf("  sleep(%d);\n", totalDelay))
					accumulatedDelay = 0
				}
			} else {
				// 累积延迟
				accumulatedDelay += delay
			}
		}

		// 生成事件代码
		g.generateEvent(&sb, ev)

		// 更新最后的事件类型
		lastEventType = ev.Type
	}

	// 输出剩余的累积延迟
	if accumulatedDelay >= int64(g.MinDelayThreshold) {
		sb.WriteString(fmt.Sprintf("  sleep(%d);\n", accumulatedDelay))
	}

	sb.WriteString(`}

main();
`)

	return sb.String(), nil
}

// shouldAddSleep 判断是否需要添加 sleep
func (g *Generator) shouldAddSleep(currentType, lastType model.EventType, delay, accumulated int64) bool {
	// 延迟太小，不需要 sleep
	if delay < int64(g.MinDelayThreshold) && accumulated == 0 {
		return false
	}

	// 连续的键盘事件（同一按键的 KeyDown -> KeyUp）之间不需要 sleep
	if currentType == model.EventTypeKeyUp && lastType == model.EventTypeKeyDown {
		return false
	}

	// 连续的鼠标移动不需要 sleep
	if currentType == model.EventTypeMouseMove && lastType == model.EventTypeMouseMove {
		return false
	}

	// 连续的 KeyDown 事件（快速打字）可以累积延迟
	if currentType == model.EventTypeKeyDown && lastType == model.EventTypeKeyDown {
		return false
	}

	// 鼠标按下和释放之间不需要 sleep
	if (currentType == model.EventTypeMouseUp && lastType == model.EventTypeMouseDown) ||
		(currentType == model.EventTypeMouseDown && lastType == model.EventTypeMouseUp) {
		return false
	}

	// 其他情况根据累积延迟判断
	return (accumulated + delay) >= int64(g.MinDelayThreshold)
}

// generateEvent 生成单个事件代码
func (g *Generator) generateEvent(sb *strings.Builder, ev model.Event) {
	switch ev.Type {
	case model.EventTypeMouseMove:
		sb.WriteString(fmt.Sprintf("  mouseMove(%d, %d);\n", ev.X, ev.Y))

	case model.EventTypeMouseDown:
		btn := g.getMouseButtonName(ev.Button)
		sb.WriteString(fmt.Sprintf("  mouseClick('%s');\n", btn))

	case model.EventTypeMouseUp:
		// mouseup 通常不需要单独处理，因为 click 已经包含

	case model.EventTypeMouseWheel, model.EventTypeWheelUp, model.EventTypeWheelDown:
		sb.WriteString(fmt.Sprintf("  mouseScroll(%d);\n", ev.Delta))

	case model.EventTypeKeyDown:
		keyName := g.getKeyName(ev.Chars)
		sb.WriteString(fmt.Sprintf("  keyDown('%s');\n", keyName))
		sb.WriteString(fmt.Sprintf("  keyUp('%s');\n", keyName))
		// case model.EventTypeKeyUp:
		// 	keyName := g.getKeyName(ev.KeyCode)
		// 	sb.WriteString(fmt.Sprintf("  keyUp('%s');\n", keyName))

	case model.Selection:
		// 文字选择事件，记录选中的文字
		if ev.Text != "" {
			escapedText := escapeJavaScriptString(ev.Text)
			sb.WriteString(fmt.Sprintf("  let selectedText = getSelectedText(); // 选中: %s\n", escapedText))
		}
	}
}

// optimizeEvents 优化事件序列
func (g *Generator) optimizeEvents(events []model.Event) []model.Event {
	if len(events) == 0 {
		return events
	}

	// 移除重复的 mousemove 事件（保留最新的）
	optimized := make([]model.Event, 0)
	lastMouseMove := model.Event{}
	var lastMouseMoveExists bool

	for _, ev := range events {
		// 处理鼠标移动事件
		if ev.Type == model.EventTypeMouseMove {
			// 如果是连续的 mousemove，只保留最后一个
			lastMouseMove = ev
			lastMouseMoveExists = true
		} else {
			// 如果有累积的 mousemove，先添加它
			if lastMouseMoveExists {
				optimized = append(optimized, lastMouseMove)
				lastMouseMove = model.Event{}
				lastMouseMoveExists = false
			}
			optimized = append(optimized, ev)
		}
	}

	// 处理末尾的 mousemove
	if lastMouseMoveExists {
		optimized = append(optimized, lastMouseMove)
	}

	return optimized
}

// getMouseButtonName 获取鼠标按钮名称
func (g *Generator) getMouseButtonName(btn model.MouseButton) string {
	switch btn {
	case model.MouseButtonLeft:
		return "left"
	case model.MouseButtonRight:
		return "right"
	case model.MouseButtonMiddle:
		return "middle"
	default:
		return "left"
	}
}

// getKeyName 获取按键名称（使用统一的键码映射）
func (g *Generator) getKeyName(keyCode int) string {
	// 使用 model 包中定义的统一键码映射
	name := model.GetKeyNameByScanCode(keyCode)

	// 如果是未知键，记录警告
	if strings.HasPrefix(name, "key_") {
		fmt.Printf("[DEBUG] Unknown keycode: %d (0x%X)\n", keyCode, keyCode)
	}

	return model.NormalizeKeyName(name)
}

// escapeJavaScriptString 转义 JavaScript 字符串
func escapeJavaScriptString(s string) string {
	result := strings.Builder{}
	for _, ch := range s {
		switch ch {
		case '\\':
			result.WriteString("\\\\")
		case '"':
			result.WriteString("\\\"")
		case '\n':
			result.WriteString("\\n")
		case '\r':
			result.WriteString("\\r")
		case '\t':
			result.WriteString("\\t")
		default:
			result.WriteRune(ch)
		}
	}
	return result.String()
}
