// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMacro(arg1) {
  return window['go']['main']['App']['DeleteMacro'](arg1);
}

export function GenerateCurrentScript() {
  return window['go']['main']['App']['GenerateCurrentScript']();
}

export function GenerateScript(arg1) {
  return window['go']['main']['App']['GenerateScript'](arg1);
}

export function GetEventCount() {
  return window['go']['main']['App']['GetEventCount']();
}

export function GetRecentEvents(arg1) {
  return window['go']['main']['App']['GetRecentEvents'](arg1);
}

export function IsEngineRunning() {
  return window['go']['main']['App']['IsEngineRunning']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function ListMacros() {
  return window['go']['main']['App']['ListMacros']();
}

export function LoadMacro(arg1) {
  return window['go']['main']['App']['LoadMacro'](arg1);
}

export function PlayScript(arg1) {
  return window['go']['main']['App']['PlayScript'](arg1);
}

export function SaveMacro(arg1, arg2) {
  return window['go']['main']['App']['SaveMacro'](arg1, arg2);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
