// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteMacro(arg1:string):Promise<void>;

export function GenerateCurrentScript():Promise<string>;

export function GenerateScript(arg1:string):Promise<string>;

export function GetEventCount():Promise<number>;

export function GetRecentEvents(arg1:number):Promise<Array<main.EventInfo>>;

export function IsEngineRunning():Promise<boolean>;

export function IsRecording():Promise<boolean>;

export function ListMacros():Promise<Array<main.MacroInfo>>;

export function LoadMacro(arg1:string):Promise<string>;

export function PlayScript(arg1:string):Promise<void>;

export function SaveMacro(arg1:string,arg2:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<number>;
