// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: macro.proto

package macro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearPrevious bool                   `protobuf:"varint,1,opt,name=clear_previous,json=clearPrevious,proto3" json:"clear_previous,omitempty"` // 是否清除之前的事件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecordingRequest) Reset() {
	*x = StartRecordingRequest{}
	mi := &file_macro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordingRequest) ProtoMessage() {}

func (x *StartRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordingRequest.ProtoReflect.Descriptor instead.
func (*StartRecordingRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{0}
}

func (x *StartRecordingRequest) GetClearPrevious() bool {
	if x != nil {
		return x.ClearPrevious
	}
	return false
}

type StartRecordingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecordingResponse) Reset() {
	*x = StartRecordingResponse{}
	mi := &file_macro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordingResponse) ProtoMessage() {}

func (x *StartRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordingResponse.ProtoReflect.Descriptor instead.
func (*StartRecordingResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{1}
}

func (x *StartRecordingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRecordingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingRequest) Reset() {
	*x = StopRecordingRequest{}
	mi := &file_macro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingRequest) ProtoMessage() {}

func (x *StopRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingRequest.ProtoReflect.Descriptor instead.
func (*StopRecordingRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{2}
}

type StopRecordingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EventCount    int32                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingResponse) Reset() {
	*x = StopRecordingResponse{}
	mi := &file_macro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingResponse) ProtoMessage() {}

func (x *StopRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingResponse.ProtoReflect.Descriptor instead.
func (*StopRecordingResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{3}
}

func (x *StopRecordingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopRecordingResponse) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *StopRecordingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRecordingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordingStatusRequest) Reset() {
	*x = GetRecordingStatusRequest{}
	mi := &file_macro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordingStatusRequest) ProtoMessage() {}

func (x *GetRecordingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordingStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRecordingStatusRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{4}
}

type GetRecordingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRecording   bool                   `protobuf:"varint,1,opt,name=is_recording,json=isRecording,proto3" json:"is_recording,omitempty"`
	EventCount    int32                  `protobuf:"varint,2,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordingStatusResponse) Reset() {
	*x = GetRecordingStatusResponse{}
	mi := &file_macro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordingStatusResponse) ProtoMessage() {}

func (x *GetRecordingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordingStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRecordingStatusResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecordingStatusResponse) GetIsRecording() bool {
	if x != nil {
		return x.IsRecording
	}
	return false
}

func (x *GetRecordingStatusResponse) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

type PlayScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	Speed         float64                `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"` // 播放速度倍率 (1.0 = 正常)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayScriptRequest) Reset() {
	*x = PlayScriptRequest{}
	mi := &file_macro_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayScriptRequest) ProtoMessage() {}

func (x *PlayScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayScriptRequest.ProtoReflect.Descriptor instead.
func (*PlayScriptRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{6}
}

func (x *PlayScriptRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *PlayScriptRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type PlayScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayScriptResponse) Reset() {
	*x = PlayScriptResponse{}
	mi := &file_macro_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayScriptResponse) ProtoMessage() {}

func (x *PlayScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayScriptResponse.ProtoReflect.Descriptor instead.
func (*PlayScriptResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{7}
}

func (x *PlayScriptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayScriptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPlaybackStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaybackStatusRequest) Reset() {
	*x = GetPlaybackStatusRequest{}
	mi := &file_macro_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaybackStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaybackStatusRequest) ProtoMessage() {}

func (x *GetPlaybackStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaybackStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPlaybackStatusRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{8}
}

type GetPlaybackStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPlaying     bool                   `protobuf:"varint,1,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"` // 进度百分比
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaybackStatusResponse) Reset() {
	*x = GetPlaybackStatusResponse{}
	mi := &file_macro_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaybackStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaybackStatusResponse) ProtoMessage() {}

func (x *GetPlaybackStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaybackStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPlaybackStatusResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{9}
}

func (x *GetPlaybackStatusResponse) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *GetPlaybackStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type MacroInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EventCount    int32                  `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	Script        string                 `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"` // 脚本内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MacroInfo) Reset() {
	*x = MacroInfo{}
	mi := &file_macro_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MacroInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacroInfo) ProtoMessage() {}

func (x *MacroInfo) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacroInfo.ProtoReflect.Descriptor instead.
func (*MacroInfo) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{10}
}

func (x *MacroInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MacroInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MacroInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MacroInfo) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *MacroInfo) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type SaveMacroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMacroRequest) Reset() {
	*x = SaveMacroRequest{}
	mi := &file_macro_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMacroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMacroRequest) ProtoMessage() {}

func (x *SaveMacroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMacroRequest.ProtoReflect.Descriptor instead.
func (*SaveMacroRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{11}
}

func (x *SaveMacroRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveMacroRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type SaveMacroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMacroResponse) Reset() {
	*x = SaveMacroResponse{}
	mi := &file_macro_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMacroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMacroResponse) ProtoMessage() {}

func (x *SaveMacroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMacroResponse.ProtoReflect.Descriptor instead.
func (*SaveMacroResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{12}
}

func (x *SaveMacroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveMacroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoadMacroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMacroRequest) Reset() {
	*x = LoadMacroRequest{}
	mi := &file_macro_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMacroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMacroRequest) ProtoMessage() {}

func (x *LoadMacroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMacroRequest.ProtoReflect.Descriptor instead.
func (*LoadMacroRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{13}
}

func (x *LoadMacroRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoadMacroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Macro         *MacroInfo             `protobuf:"bytes,2,opt,name=macro,proto3" json:"macro,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMacroResponse) Reset() {
	*x = LoadMacroResponse{}
	mi := &file_macro_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMacroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMacroResponse) ProtoMessage() {}

func (x *LoadMacroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMacroResponse.ProtoReflect.Descriptor instead.
func (*LoadMacroResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{14}
}

func (x *LoadMacroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadMacroResponse) GetMacro() *MacroInfo {
	if x != nil {
		return x.Macro
	}
	return nil
}

func (x *LoadMacroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteMacroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMacroRequest) Reset() {
	*x = DeleteMacroRequest{}
	mi := &file_macro_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMacroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMacroRequest) ProtoMessage() {}

func (x *DeleteMacroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMacroRequest.ProtoReflect.Descriptor instead.
func (*DeleteMacroRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteMacroRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteMacroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMacroResponse) Reset() {
	*x = DeleteMacroResponse{}
	mi := &file_macro_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMacroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMacroResponse) ProtoMessage() {}

func (x *DeleteMacroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMacroResponse.ProtoReflect.Descriptor instead.
func (*DeleteMacroResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteMacroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMacroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListMacrosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMacrosRequest) Reset() {
	*x = ListMacrosRequest{}
	mi := &file_macro_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMacrosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMacrosRequest) ProtoMessage() {}

func (x *ListMacrosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMacrosRequest.ProtoReflect.Descriptor instead.
func (*ListMacrosRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{17}
}

type ListMacrosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Macros        []*MacroInfo           `protobuf:"bytes,2,rep,name=macros,proto3" json:"macros,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMacrosResponse) Reset() {
	*x = ListMacrosResponse{}
	mi := &file_macro_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMacrosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMacrosResponse) ProtoMessage() {}

func (x *ListMacrosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMacrosResponse.ProtoReflect.Descriptor instead.
func (*ListMacrosResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{18}
}

func (x *ListMacrosResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListMacrosResponse) GetMacros() []*MacroInfo {
	if x != nil {
		return x.Macros
	}
	return nil
}

func (x *ListMacrosResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScriptRequest) Reset() {
	*x = GenerateScriptRequest{}
	mi := &file_macro_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScriptRequest) ProtoMessage() {}

func (x *GenerateScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScriptRequest.ProtoReflect.Descriptor instead.
func (*GenerateScriptRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{19}
}

func (x *GenerateScriptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GenerateScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateScriptResponse) Reset() {
	*x = GenerateScriptResponse{}
	mi := &file_macro_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateScriptResponse) ProtoMessage() {}

func (x *GenerateScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateScriptResponse.ProtoReflect.Descriptor instead.
func (*GenerateScriptResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateScriptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateScriptResponse) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *GenerateScriptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                       // 事件类型: keydown, keyup, mousedown, mouseup, mousemove, wheel
	KeyCode       int32                  `protobuf:"varint,2,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"` // 键值
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`                            // X 坐标
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`                            // Y 坐标
	Button        int32                  `protobuf:"varint,5,opt,name=button,proto3" json:"button,omitempty"`                  // 鼠标按钮
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`            // 时间戳
	Delta         int32                  `protobuf:"varint,7,opt,name=delta,proto3" json:"delta,omitempty"`                    // 滚轮增量
	Chars         string                 `protobuf:"bytes,8,opt,name=chars,proto3" json:"chars,omitempty"`                     // 字符（用于字符输入事件）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_macro_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{21}
}

func (x *EventData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventData) GetKeyCode() int32 {
	if x != nil {
		return x.KeyCode
	}
	return 0
}

func (x *EventData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EventData) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EventData) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *EventData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EventData) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *EventData) GetChars() string {
	if x != nil {
		return x.Chars
	}
	return ""
}

type GetCurrentEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentEventsRequest) Reset() {
	*x = GetCurrentEventsRequest{}
	mi := &file_macro_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentEventsRequest) ProtoMessage() {}

func (x *GetCurrentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentEventsRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentEventsRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{22}
}

type GetCurrentEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Events        []*EventData           `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentEventsResponse) Reset() {
	*x = GetCurrentEventsResponse{}
	mi := &file_macro_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentEventsResponse) ProtoMessage() {}

func (x *GetCurrentEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentEventsResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentEventsResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{23}
}

func (x *GetCurrentEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCurrentEventsResponse) GetEvents() []*EventData {
	if x != nil {
		return x.Events
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_macro_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{24}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_macro_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_macro_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_macro_proto_rawDescGZIP(), []int{25}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_macro_proto protoreflect.FileDescriptor

const file_macro_proto_rawDesc = "" +
	"\n" +
	"\vmacro.proto\x12\x05macro\">\n" +
	"\x15StartRecordingRequest\x12%\n" +
	"\x0eclear_previous\x18\x01 \x01(\bR\rclearPrevious\"L\n" +
	"\x16StartRecordingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14StopRecordingRequest\"l\n" +
	"\x15StopRecordingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x05R\n" +
	"eventCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x1b\n" +
	"\x19GetRecordingStatusRequest\"`\n" +
	"\x1aGetRecordingStatusResponse\x12!\n" +
	"\fis_recording\x18\x01 \x01(\bR\visRecording\x12\x1f\n" +
	"\vevent_count\x18\x02 \x01(\x05R\n" +
	"eventCount\"A\n" +
	"\x11PlayScriptRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x01R\x05speed\"H\n" +
	"\x12PlayScriptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\x18GetPlaybackStatusRequest\"V\n" +
	"\x19GetPlaybackStatusResponse\x12\x1d\n" +
	"\n" +
	"is_playing\x18\x01 \x01(\bR\tisPlaying\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\"\x96\x01\n" +
	"\tMacroInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x05R\n" +
	"eventCount\x12\x16\n" +
	"\x06script\x18\x05 \x01(\tR\x06script\">\n" +
	"\x10SaveMacroRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\"G\n" +
	"\x11SaveMacroResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x10LoadMacroRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"o\n" +
	"\x11LoadMacroResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05macro\x18\x02 \x01(\v2\x10.macro.MacroInfoR\x05macro\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"(\n" +
	"\x12DeleteMacroRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x13DeleteMacroResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListMacrosRequest\"r\n" +
	"\x12ListMacrosResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x06macros\x18\x02 \x03(\v2\x10.macro.MacroInfoR\x06macros\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"+\n" +
	"\x15GenerateScriptRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"d\n" +
	"\x16GenerateScriptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb8\x01\n" +
	"\tEventData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bkey_code\x18\x02 \x01(\x05R\akeyCode\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x16\n" +
	"\x06button\x18\x05 \x01(\x05R\x06button\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05delta\x18\a \x01(\x05R\x05delta\x12\x14\n" +
	"\x05chars\x18\b \x01(\tR\x05chars\"\x19\n" +
	"\x17GetCurrentEventsRequest\"^\n" +
	"\x18GetCurrentEventsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x06events\x18\x02 \x03(\v2\x10.macro.EventDataR\x06events\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x91\a\n" +
	"\vMacroEngine\x12M\n" +
	"\x0eStartRecording\x12\x1c.macro.StartRecordingRequest\x1a\x1d.macro.StartRecordingResponse\x12J\n" +
	"\rStopRecording\x12\x1b.macro.StopRecordingRequest\x1a\x1c.macro.StopRecordingResponse\x12Y\n" +
	"\x12GetRecordingStatus\x12 .macro.GetRecordingStatusRequest\x1a!.macro.GetRecordingStatusResponse\x12A\n" +
	"\n" +
	"PlayScript\x12\x18.macro.PlayScriptRequest\x1a\x19.macro.PlayScriptResponse\x12V\n" +
	"\x11GetPlaybackStatus\x12\x1f.macro.GetPlaybackStatusRequest\x1a .macro.GetPlaybackStatusResponse\x12>\n" +
	"\tSaveMacro\x12\x17.macro.SaveMacroRequest\x1a\x18.macro.SaveMacroResponse\x12>\n" +
	"\tLoadMacro\x12\x17.macro.LoadMacroRequest\x1a\x18.macro.LoadMacroResponse\x12D\n" +
	"\vDeleteMacro\x12\x19.macro.DeleteMacroRequest\x1a\x1a.macro.DeleteMacroResponse\x12A\n" +
	"\n" +
	"ListMacros\x12\x18.macro.ListMacrosRequest\x1a\x19.macro.ListMacrosResponse\x12M\n" +
	"\x0eGenerateScript\x12\x1c.macro.GenerateScriptRequest\x1a\x1d.macro.GenerateScriptResponse\x12S\n" +
	"\x10GetCurrentEvents\x12\x1e.macro.GetCurrentEventsRequest\x1a\x1f.macro.GetCurrentEventsResponse\x12D\n" +
	"\vHealthCheck\x12\x19.macro.HealthCheckRequest\x1a\x1a.macro.HealthCheckResponseB=Z;github.com/issueye/macro-operation/macro-common/proto;macrob\x06proto3"

var (
	file_macro_proto_rawDescOnce sync.Once
	file_macro_proto_rawDescData []byte
)

func file_macro_proto_rawDescGZIP() []byte {
	file_macro_proto_rawDescOnce.Do(func() {
		file_macro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_macro_proto_rawDesc), len(file_macro_proto_rawDesc)))
	})
	return file_macro_proto_rawDescData
}

var file_macro_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_macro_proto_goTypes = []any{
	(*StartRecordingRequest)(nil),      // 0: macro.StartRecordingRequest
	(*StartRecordingResponse)(nil),     // 1: macro.StartRecordingResponse
	(*StopRecordingRequest)(nil),       // 2: macro.StopRecordingRequest
	(*StopRecordingResponse)(nil),      // 3: macro.StopRecordingResponse
	(*GetRecordingStatusRequest)(nil),  // 4: macro.GetRecordingStatusRequest
	(*GetRecordingStatusResponse)(nil), // 5: macro.GetRecordingStatusResponse
	(*PlayScriptRequest)(nil),          // 6: macro.PlayScriptRequest
	(*PlayScriptResponse)(nil),         // 7: macro.PlayScriptResponse
	(*GetPlaybackStatusRequest)(nil),   // 8: macro.GetPlaybackStatusRequest
	(*GetPlaybackStatusResponse)(nil),  // 9: macro.GetPlaybackStatusResponse
	(*MacroInfo)(nil),                  // 10: macro.MacroInfo
	(*SaveMacroRequest)(nil),           // 11: macro.SaveMacroRequest
	(*SaveMacroResponse)(nil),          // 12: macro.SaveMacroResponse
	(*LoadMacroRequest)(nil),           // 13: macro.LoadMacroRequest
	(*LoadMacroResponse)(nil),          // 14: macro.LoadMacroResponse
	(*DeleteMacroRequest)(nil),         // 15: macro.DeleteMacroRequest
	(*DeleteMacroResponse)(nil),        // 16: macro.DeleteMacroResponse
	(*ListMacrosRequest)(nil),          // 17: macro.ListMacrosRequest
	(*ListMacrosResponse)(nil),         // 18: macro.ListMacrosResponse
	(*GenerateScriptRequest)(nil),      // 19: macro.GenerateScriptRequest
	(*GenerateScriptResponse)(nil),     // 20: macro.GenerateScriptResponse
	(*EventData)(nil),                  // 21: macro.EventData
	(*GetCurrentEventsRequest)(nil),    // 22: macro.GetCurrentEventsRequest
	(*GetCurrentEventsResponse)(nil),   // 23: macro.GetCurrentEventsResponse
	(*HealthCheckRequest)(nil),         // 24: macro.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 25: macro.HealthCheckResponse
}
var file_macro_proto_depIdxs = []int32{
	10, // 0: macro.LoadMacroResponse.macro:type_name -> macro.MacroInfo
	10, // 1: macro.ListMacrosResponse.macros:type_name -> macro.MacroInfo
	21, // 2: macro.GetCurrentEventsResponse.events:type_name -> macro.EventData
	0,  // 3: macro.MacroEngine.StartRecording:input_type -> macro.StartRecordingRequest
	2,  // 4: macro.MacroEngine.StopRecording:input_type -> macro.StopRecordingRequest
	4,  // 5: macro.MacroEngine.GetRecordingStatus:input_type -> macro.GetRecordingStatusRequest
	6,  // 6: macro.MacroEngine.PlayScript:input_type -> macro.PlayScriptRequest
	8,  // 7: macro.MacroEngine.GetPlaybackStatus:input_type -> macro.GetPlaybackStatusRequest
	11, // 8: macro.MacroEngine.SaveMacro:input_type -> macro.SaveMacroRequest
	13, // 9: macro.MacroEngine.LoadMacro:input_type -> macro.LoadMacroRequest
	15, // 10: macro.MacroEngine.DeleteMacro:input_type -> macro.DeleteMacroRequest
	17, // 11: macro.MacroEngine.ListMacros:input_type -> macro.ListMacrosRequest
	19, // 12: macro.MacroEngine.GenerateScript:input_type -> macro.GenerateScriptRequest
	22, // 13: macro.MacroEngine.GetCurrentEvents:input_type -> macro.GetCurrentEventsRequest
	24, // 14: macro.MacroEngine.HealthCheck:input_type -> macro.HealthCheckRequest
	1,  // 15: macro.MacroEngine.StartRecording:output_type -> macro.StartRecordingResponse
	3,  // 16: macro.MacroEngine.StopRecording:output_type -> macro.StopRecordingResponse
	5,  // 17: macro.MacroEngine.GetRecordingStatus:output_type -> macro.GetRecordingStatusResponse
	7,  // 18: macro.MacroEngine.PlayScript:output_type -> macro.PlayScriptResponse
	9,  // 19: macro.MacroEngine.GetPlaybackStatus:output_type -> macro.GetPlaybackStatusResponse
	12, // 20: macro.MacroEngine.SaveMacro:output_type -> macro.SaveMacroResponse
	14, // 21: macro.MacroEngine.LoadMacro:output_type -> macro.LoadMacroResponse
	16, // 22: macro.MacroEngine.DeleteMacro:output_type -> macro.DeleteMacroResponse
	18, // 23: macro.MacroEngine.ListMacros:output_type -> macro.ListMacrosResponse
	20, // 24: macro.MacroEngine.GenerateScript:output_type -> macro.GenerateScriptResponse
	23, // 25: macro.MacroEngine.GetCurrentEvents:output_type -> macro.GetCurrentEventsResponse
	25, // 26: macro.MacroEngine.HealthCheck:output_type -> macro.HealthCheckResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_macro_proto_init() }
func file_macro_proto_init() {
	if File_macro_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_macro_proto_rawDesc), len(file_macro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_macro_proto_goTypes,
		DependencyIndexes: file_macro_proto_depIdxs,
		MessageInfos:      file_macro_proto_msgTypes,
	}.Build()
	File_macro_proto = out.File
	file_macro_proto_goTypes = nil
	file_macro_proto_depIdxs = nil
}
