// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.20.1
// source: proto/macro.proto

package macro

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MacroEngine_StartRecording_FullMethodName     = "/macro.MacroEngine/StartRecording"
	MacroEngine_StopRecording_FullMethodName      = "/macro.MacroEngine/StopRecording"
	MacroEngine_GetRecordingStatus_FullMethodName = "/macro.MacroEngine/GetRecordingStatus"
	MacroEngine_PlayScript_FullMethodName         = "/macro.MacroEngine/PlayScript"
	MacroEngine_GetPlaybackStatus_FullMethodName  = "/macro.MacroEngine/GetPlaybackStatus"
	MacroEngine_SaveMacro_FullMethodName          = "/macro.MacroEngine/SaveMacro"
	MacroEngine_LoadMacro_FullMethodName          = "/macro.MacroEngine/LoadMacro"
	MacroEngine_DeleteMacro_FullMethodName        = "/macro.MacroEngine/DeleteMacro"
	MacroEngine_ListMacros_FullMethodName         = "/macro.MacroEngine/ListMacros"
	MacroEngine_GenerateScript_FullMethodName     = "/macro.MacroEngine/GenerateScript"
	MacroEngine_GetCurrentEvents_FullMethodName   = "/macro.MacroEngine/GetCurrentEvents"
	MacroEngine_HealthCheck_FullMethodName        = "/macro.MacroEngine/HealthCheck"
)

// MacroEngineClient is the client API for MacroEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 宏自动化引擎服务
type MacroEngineClient interface {
	// 录制控制
	StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error)
	StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*StopRecordingResponse, error)
	GetRecordingStatus(ctx context.Context, in *GetRecordingStatusRequest, opts ...grpc.CallOption) (*GetRecordingStatusResponse, error)
	// 回放控制
	PlayScript(ctx context.Context, in *PlayScriptRequest, opts ...grpc.CallOption) (*PlayScriptResponse, error)
	GetPlaybackStatus(ctx context.Context, in *GetPlaybackStatusRequest, opts ...grpc.CallOption) (*GetPlaybackStatusResponse, error)
	// 宏管理
	SaveMacro(ctx context.Context, in *SaveMacroRequest, opts ...grpc.CallOption) (*SaveMacroResponse, error)
	LoadMacro(ctx context.Context, in *LoadMacroRequest, opts ...grpc.CallOption) (*LoadMacroResponse, error)
	DeleteMacro(ctx context.Context, in *DeleteMacroRequest, opts ...grpc.CallOption) (*DeleteMacroResponse, error)
	ListMacros(ctx context.Context, in *ListMacrosRequest, opts ...grpc.CallOption) (*ListMacrosResponse, error)
	// 脚本生成
	GenerateScript(ctx context.Context, in *GenerateScriptRequest, opts ...grpc.CallOption) (*GenerateScriptResponse, error)
	GetCurrentEvents(ctx context.Context, in *GetCurrentEventsRequest, opts ...grpc.CallOption) (*GetCurrentEventsResponse, error)
	// 系统
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type macroEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMacroEngineClient(cc grpc.ClientConnInterface) MacroEngineClient {
	return &macroEngineClient{cc}
}

func (c *macroEngineClient) StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRecordingResponse)
	err := c.cc.Invoke(ctx, MacroEngine_StartRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*StopRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRecordingResponse)
	err := c.cc.Invoke(ctx, MacroEngine_StopRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) GetRecordingStatus(ctx context.Context, in *GetRecordingStatusRequest, opts ...grpc.CallOption) (*GetRecordingStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecordingStatusResponse)
	err := c.cc.Invoke(ctx, MacroEngine_GetRecordingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) PlayScript(ctx context.Context, in *PlayScriptRequest, opts ...grpc.CallOption) (*PlayScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayScriptResponse)
	err := c.cc.Invoke(ctx, MacroEngine_PlayScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) GetPlaybackStatus(ctx context.Context, in *GetPlaybackStatusRequest, opts ...grpc.CallOption) (*GetPlaybackStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaybackStatusResponse)
	err := c.cc.Invoke(ctx, MacroEngine_GetPlaybackStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) SaveMacro(ctx context.Context, in *SaveMacroRequest, opts ...grpc.CallOption) (*SaveMacroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMacroResponse)
	err := c.cc.Invoke(ctx, MacroEngine_SaveMacro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) LoadMacro(ctx context.Context, in *LoadMacroRequest, opts ...grpc.CallOption) (*LoadMacroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadMacroResponse)
	err := c.cc.Invoke(ctx, MacroEngine_LoadMacro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) DeleteMacro(ctx context.Context, in *DeleteMacroRequest, opts ...grpc.CallOption) (*DeleteMacroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMacroResponse)
	err := c.cc.Invoke(ctx, MacroEngine_DeleteMacro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) ListMacros(ctx context.Context, in *ListMacrosRequest, opts ...grpc.CallOption) (*ListMacrosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMacrosResponse)
	err := c.cc.Invoke(ctx, MacroEngine_ListMacros_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) GenerateScript(ctx context.Context, in *GenerateScriptRequest, opts ...grpc.CallOption) (*GenerateScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateScriptResponse)
	err := c.cc.Invoke(ctx, MacroEngine_GenerateScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) GetCurrentEvents(ctx context.Context, in *GetCurrentEventsRequest, opts ...grpc.CallOption) (*GetCurrentEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentEventsResponse)
	err := c.cc.Invoke(ctx, MacroEngine_GetCurrentEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *macroEngineClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MacroEngine_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MacroEngineServer is the server API for MacroEngine service.
// All implementations must embed UnimplementedMacroEngineServer
// for forward compatibility.
//
// 宏自动化引擎服务
type MacroEngineServer interface {
	// 录制控制
	StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error)
	StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error)
	GetRecordingStatus(context.Context, *GetRecordingStatusRequest) (*GetRecordingStatusResponse, error)
	// 回放控制
	PlayScript(context.Context, *PlayScriptRequest) (*PlayScriptResponse, error)
	GetPlaybackStatus(context.Context, *GetPlaybackStatusRequest) (*GetPlaybackStatusResponse, error)
	// 宏管理
	SaveMacro(context.Context, *SaveMacroRequest) (*SaveMacroResponse, error)
	LoadMacro(context.Context, *LoadMacroRequest) (*LoadMacroResponse, error)
	DeleteMacro(context.Context, *DeleteMacroRequest) (*DeleteMacroResponse, error)
	ListMacros(context.Context, *ListMacrosRequest) (*ListMacrosResponse, error)
	// 脚本生成
	GenerateScript(context.Context, *GenerateScriptRequest) (*GenerateScriptResponse, error)
	GetCurrentEvents(context.Context, *GetCurrentEventsRequest) (*GetCurrentEventsResponse, error)
	// 系统
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMacroEngineServer()
}

// UnimplementedMacroEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMacroEngineServer struct{}

func (UnimplementedMacroEngineServer) StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRecording not implemented")
}
func (UnimplementedMacroEngineServer) StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecording not implemented")
}
func (UnimplementedMacroEngineServer) GetRecordingStatus(context.Context, *GetRecordingStatusRequest) (*GetRecordingStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecordingStatus not implemented")
}
func (UnimplementedMacroEngineServer) PlayScript(context.Context, *PlayScriptRequest) (*PlayScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayScript not implemented")
}
func (UnimplementedMacroEngineServer) GetPlaybackStatus(context.Context, *GetPlaybackStatusRequest) (*GetPlaybackStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaybackStatus not implemented")
}
func (UnimplementedMacroEngineServer) SaveMacro(context.Context, *SaveMacroRequest) (*SaveMacroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveMacro not implemented")
}
func (UnimplementedMacroEngineServer) LoadMacro(context.Context, *LoadMacroRequest) (*LoadMacroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadMacro not implemented")
}
func (UnimplementedMacroEngineServer) DeleteMacro(context.Context, *DeleteMacroRequest) (*DeleteMacroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMacro not implemented")
}
func (UnimplementedMacroEngineServer) ListMacros(context.Context, *ListMacrosRequest) (*ListMacrosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMacros not implemented")
}
func (UnimplementedMacroEngineServer) GenerateScript(context.Context, *GenerateScriptRequest) (*GenerateScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateScript not implemented")
}
func (UnimplementedMacroEngineServer) GetCurrentEvents(context.Context, *GetCurrentEventsRequest) (*GetCurrentEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentEvents not implemented")
}
func (UnimplementedMacroEngineServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMacroEngineServer) mustEmbedUnimplementedMacroEngineServer() {}
func (UnimplementedMacroEngineServer) testEmbeddedByValue()                     {}

// UnsafeMacroEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MacroEngineServer will
// result in compilation errors.
type UnsafeMacroEngineServer interface {
	mustEmbedUnimplementedMacroEngineServer()
}

func RegisterMacroEngineServer(s grpc.ServiceRegistrar, srv MacroEngineServer) {
	// If the following call panics, it indicates UnimplementedMacroEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MacroEngine_ServiceDesc, srv)
}

func _MacroEngine_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_StartRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).StartRecording(ctx, req.(*StartRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_StopRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).StopRecording(ctx, req.(*StopRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_GetRecordingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).GetRecordingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_GetRecordingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).GetRecordingStatus(ctx, req.(*GetRecordingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_PlayScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).PlayScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_PlayScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).PlayScript(ctx, req.(*PlayScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_GetPlaybackStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaybackStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).GetPlaybackStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_GetPlaybackStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).GetPlaybackStatus(ctx, req.(*GetPlaybackStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_SaveMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMacroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).SaveMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_SaveMacro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).SaveMacro(ctx, req.(*SaveMacroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_LoadMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMacroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).LoadMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_LoadMacro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).LoadMacro(ctx, req.(*LoadMacroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_DeleteMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMacroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).DeleteMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_DeleteMacro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).DeleteMacro(ctx, req.(*DeleteMacroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_ListMacros_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMacrosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).ListMacros(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_ListMacros_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).ListMacros(ctx, req.(*ListMacrosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_GenerateScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).GenerateScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_GenerateScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).GenerateScript(ctx, req.(*GenerateScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_GetCurrentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).GetCurrentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_GetCurrentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).GetCurrentEvents(ctx, req.(*GetCurrentEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MacroEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacroEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacroEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacroEngineServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MacroEngine_ServiceDesc is the grpc.ServiceDesc for MacroEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MacroEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "macro.MacroEngine",
	HandlerType: (*MacroEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRecording",
			Handler:    _MacroEngine_StartRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _MacroEngine_StopRecording_Handler,
		},
		{
			MethodName: "GetRecordingStatus",
			Handler:    _MacroEngine_GetRecordingStatus_Handler,
		},
		{
			MethodName: "PlayScript",
			Handler:    _MacroEngine_PlayScript_Handler,
		},
		{
			MethodName: "GetPlaybackStatus",
			Handler:    _MacroEngine_GetPlaybackStatus_Handler,
		},
		{
			MethodName: "SaveMacro",
			Handler:    _MacroEngine_SaveMacro_Handler,
		},
		{
			MethodName: "LoadMacro",
			Handler:    _MacroEngine_LoadMacro_Handler,
		},
		{
			MethodName: "DeleteMacro",
			Handler:    _MacroEngine_DeleteMacro_Handler,
		},
		{
			MethodName: "ListMacros",
			Handler:    _MacroEngine_ListMacros_Handler,
		},
		{
			MethodName: "GenerateScript",
			Handler:    _MacroEngine_GenerateScript_Handler,
		},
		{
			MethodName: "GetCurrentEvents",
			Handler:    _MacroEngine_GetCurrentEvents_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MacroEngine_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/macro.proto",
}
