// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteMacro(arg1:string):Promise<void>;

export function GenerateCurrentScript():Promise<string>;

export function GetEventCount():Promise<number>;

export function IsRecording():Promise<boolean>;

export function ListMacros():Promise<Array<model.Macro>>;

export function PlayMacro(arg1:string):Promise<void>;

export function RecordAndSave(arg1:string):Promise<string>;

export function SaveMacro(arg1:string):Promise<string>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;
