// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMacro(arg1) {
  return window['go']['main']['App']['DeleteMacro'](arg1);
}

export function GenerateCurrentScript() {
  return window['go']['main']['App']['GenerateCurrentScript']();
}

export function GetEventCount() {
  return window['go']['main']['App']['GetEventCount']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function ListMacros() {
  return window['go']['main']['App']['ListMacros']();
}

export function PlayMacro(arg1) {
  return window['go']['main']['App']['PlayMacro'](arg1);
}

export function RecordAndSave(arg1) {
  return window['go']['main']['App']['RecordAndSave'](arg1);
}

export function SaveMacro(arg1) {
  return window['go']['main']['App']['SaveMacro'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
